### ISSUE TITLE
Nil under a MultiChildRenderObjectElement

### ISSUE THREAD

**Issue by mario202k** [letsar/nil#3]
You are using Nil under a MultiChildRenderObjectElement.
        This suggests a possibility that the Nil is not needed or is being used improperly.
        Make sure it can't be replaced with an inline conditional or
        omission of the target widget from a list.

**Comment by zigaspica** [comment]
Same problem here. Are we not supposed to use Nil widget under MultiChildRenderObjectElement or is that just a bug? @letsar

**Comment by letsar** [comment]
No, Nil cannot be used under a MultiChildRenderWidget, this widget wants only RenderObjects :-(
